name: angel
description: Sample project - designed to be a small taste of Angel.
version: 1.0.0
author: Tobe O
homepage: https://medium.com/@thosakwe/building-a-simple-file-upload-app-with-angel-64938d4ddc61
publish_to: none
dependencies:
  angel_common: ^1.0.0
  html_builder: ^1.0.0
dev_dependencies:
  http: ^0.11.3
  grinder: ^0.8.0+2
  test: ^0.12.13
